#pragma once

enum class TrapCause
{
   NONE = 0,
   ILLEGAL_INSTRUCTION,
   MISALIGNED_LOAD,
   MISALIGNED_STORE,
   LOAD_ACCESS_FAULT,
   STORE_ACCESS_FAULT,
   INSTRUCTION_ACCESS_FAULT,
   INSTRUCTION_MISALIGNED,
   STACK_SIZE_EXCEEDS_MAX,
   ECALL,
   BREAKPOINT,
   TIMER_INTERRUPT,
   EXTERNAL_INTERRUPT
};

const char *trapCauseToString(TrapCause cause);