#pragma once
#include <stddef.h>
#include <stdint.h>

constexpr uint64_t INTERRUPT_BIT = (1ULL << 63);

enum class TrapCause : uint64_t
{
   NONE = 0xFFFFFFFFFFFFFFFF,
   STACK_SIZE_EXCEEDS_MAX = 0xFFFFFFFFFFFFFFFE,

   INSTRUCTION_MISALIGNED = 0,
   INSTRUCTION_ACCESS_FAULT = 1,
   ILLEGAL_INSTRUCTION = 2,
   BREAKPOINT = 3,
   MISALIGNED_LOAD = 4,
   LOAD_ACCESS_FAULT = 5,
   MISALIGNED_STORE = 6,
   STORE_ACCESS_FAULT = 7,

   ECALL_FROM_U_MODE = 8,
   ECALL_FROM_S_MODE = 9,
   ECALL_FROM_M_MODE = 11,

   INSTRUCTION_PAGE_FAULT = 12,
   LOAD_PAGE_FAULT = 13,
   STORE_PAGE_FAULT = 15,

   SUPERVISOR_SOFTWARE_INTERRUPT = INTERRUPT_BIT | 1,
   MACHINE_SOFTWARE_INTERRUPT = INTERRUPT_BIT | 3,

   SUPERVISOR_TIMER_INTERRUPT = INTERRUPT_BIT | 5,
   MACHINE_TIMER_INTERRUPT = INTERRUPT_BIT | 7,

   SUPERVISOR_EXTERNAL_INTERRUPT = INTERRUPT_BIT | 9,
   MACHINE_EXTERNAL_INTERRUPT = INTERRUPT_BIT | 11
};

const char *trapCauseToString(TrapCause cause);